dist: trusty
sudo: required

language: python
cache:
  - pip
  - directories:
    - mysql-archives


python:
  - 2.7

env:
  - TOXENV=dj18-sqlite
  - TOXENV=dj18-mysql51
  - TOXENV=dj18-mysql57
  - FRONTEND=1

install:
  - pip install tox coveralls

script:
  - ./run_travis.sh

after_success:
  coveralls
