# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eregs_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regnode',
            name='node_id',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
