# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 22:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eregs_core', '0002_regnode_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='regnode',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
