# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eregs_core', '0003_regnode_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preamble',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='TableOfContents',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='ToCAppEntry',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='ToCSecEntry',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
    ]
