# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eregs_core', '0003_regnode_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regnode',
            name='content',
        ),
    ]
