# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eregs_core', '0004_preamble_section_tableofcontents_tocappentry_tocsecentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appendix',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='ToCEntry',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='ToCInterpEntry',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
    ]
