# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eregs_core', '0005_appendix_definition_paragraph_reference_tocentry_tocinterpentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffNode',
            fields=[
                ('regnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eregs_core.RegNode')),
                ('left_version', models.CharField(max_length=250)),
                ('right_version', models.CharField(max_length=250)),
            ],
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='AnalysisParagraph',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='AnalysisSection',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='Footnote',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
    ]
