# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eregs_core', '0005_appendix_definition_paragraph_reference_tocentry_tocinterpentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisParagraph',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='AnalysisSection',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.CreateModel(
            name='Footnote',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
    ]
