# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eregs_core', '0006_analysisparagraph_analysissection_footnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64, null=True)),
                ('left_version', models.CharField(max_length=64, null=True)),
                ('right_version', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fdsys',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
        migrations.AlterField(
            model_name='regnode',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eregs_core.Version'),
        ),
    ]
