# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eregs_core', '0009_auto_20170510_2021'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=[b'version', b'left_version', b'right_version'], name='eregs_core__version_8a9f25_idx'),
        ),
        migrations.AddIndex(
            model_name='regnode',
            index=models.Index(fields=[b'node_id'], name='eregs_core__node_id_36afbc_idx'),
        ),
        migrations.AddIndex(
            model_name='regnode',
            index=models.Index(fields=[b'label'], name='eregs_core__label_743a97_idx'),
        ),
        migrations.AddIndex(
            model_name='regnode',
            index=models.Index(fields=[b'tag'], name='eregs_core__tag_19e8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='regnode',
            index=models.Index(fields=[b'left'], name='eregs_core__left_3ce6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='regnode',
            index=models.Index(fields=[b'right'], name='eregs_core__right_f9d181_idx'),
        ),
    ]
