# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eregs_core', '0010_auto_20170511_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToCSubpartEntry',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('eregs_core.regnode',),
        ),
    ]
